"""Add scenario to sessions

Revision ID: 97c8f536f71f
Revises: f35d190931bc
Create Date: 2026-07-28 17:18:17.258024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c8f536f71f'
down_revision: Union[str, Sequence[str], None] = 'f35d190931bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('scenario', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'scenario')
    # ### end Alembic commands ###
